#more datasource-compose.yaml 
apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  orgId: 1
  url: http://127.0.0.1:9091
  basicAuth: false
  isDefault: true
  version: 1
  editable: true